export type User = {
  user_id: string; // UUID
  email: string;
  password: string;
  first_name: string;
  last_name: string;
  pet_information: string;
<<<<<<< HEAD
  user_id: string; // UUID
  order_option: boolean;
  creaed_at: string; // timestamp with time zone not null default now();
  address_id: string; // UUID
  cart: Record<string, number>; // JSONB with item as key and quantity as value
=======
  delivery_allowed: boolean;
  created_at: Date; // timestamp of when record was created
  cart_id: string; // UUID
  address_id: string; // UUID
>>>>>>> 3a6696360a9e7f891c0ff66245612853965f12cf
};

export type Order = {
  id: number; // bigint generated by default as identity
  user_id: string; // UUID not null
<<<<<<< HEAD
  cart: Record<string, number>; // JSONB with item as key and quantity as value
=======
>>>>>>> 3a6696360a9e7f891c0ff66245612853965f12cf
  status: string; // bigint null
  pickup_time: number; // bigint null
};

export type Schedule = {
  id: number; // bigint generated by default as identity
  date: Date; // text not null
  start_time: Date; // text null
  end_time: Date; // text null
};

export type Product = {
  product_id: number; // bigint generated by default as identity
  name: string; // text not null;
  description: string; // text null;
  category: string; // numeric not null;
  quantity: number; // numeric not null;
  photo: string; // text null;
  updated_at: Date; // timestamp with time zone not null default now();
};
